# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0414b76ae623ef8854a3167c2a3a6dca8dd3ca84bfc444aef3f4747cb11c9b866c899d385c3b4a0cfefaf1197daee1b0d9c808f08cea46b2acbc9fc923ecfd

test:
  secret_key_base: e2e9b0e2b979712f00e8bb47b0029b001ee108a293241adecec8b9946c9abc6ac484a213659aa27a1260dbe2e4d65f955fbfdd559b6e0e1acbc1e0600251b49d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0c0414b76ae623ef8854a3167c2a3a6dca8dd3ca84bfc444aef3f4747cb11c9b866c899d385c3b4a0cfefaf1197daee1b0d9c808f08cea46b2acbc9fc923ecfd
